### ISSUE TITLE
Image on Readme file is missing

### ISSUE THREAD

**Issue by imron02** [UADACID/react-native-auto-responsive-screen#2]
![image](https://user-images.githubusercontent.com/7010359/84635489-7af4d700-af1d-11ea-9d46-71909e764db0.png)

Please look at the image in the readme file, because the image is currently missing

**Comment by UADACID** [comment]
> ![image](https://user-images.githubusercontent.com/7010359/84635489-7af4d700-af1d-11ea-9d46-71909e764db0.png)
> 
> Please look at the image in the readme file, because the image is currently missing

This problem has been fixed and updated, thank you for reporting it @imron02
